version: '3.4'
services:
  ipfs_node_1:
    image: ipfs/go-ipfs:latest
    container_name: ipfs_node_1
    environment:
      IPFS_SWARM_KEY_FILE: /key/swarm.key
    volumes:
      - ./compose/ipfs0:/data/ipfs/
      # - /Users/sixdays/tmp/ipfs/node1/staging:/export
      # - /Users/sixdays/tmp/ipfs/node1/data:/data/ipfs
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"

  ipfs_node_2:
    image: ipfs/go-ipfs:latest
    container_name: ipfs_node_2
    environment:
      IPFS_SWARM_KEY_FILE: /key/swarm.key
    volumes:
      - ./compose/ipfs1:/data/ipfs/
      # - /Users/sixdays/tmp/ipfs/node2/staging:/export
      # - /Users/sixdays/tmp/ipfs/node2/data:/data/ipfs
    ports:
      - "4002:4001"
      - "4002:4001/udp"
      - "127.0.0.1:8081:8080"
      - "127.0.0.1:5002:5001"

# ipfs1->12D3KooWQC1RiACKGnKYLdYG82Y3N16yD8hK2xRpiooRNBRoWHLB
# add->/ip4/172.24.0.3/tcp/4001/p2p/12D3KooWQC1RiACKGnKYLdYG82Y3N16yD8hK2xRpiooRNBRoWHLB
# ipfs2->12D3KooWL1bMKySgtUFwTV7RSD43KwpGqwiZpCzbKjdJ7BA6uBdg
# add->/ip4/172.24.0.2/tcp/4001/p2p/12D3KooWL1bMKySgtUFwTV7RSD43KwpGqwiZpCzbKjdJ7BA6uBdg


  # ipfs0:
  #   container_name: ipfs0
  #   image: ipfs/go-ipfs:latest
  #   command: ["daemon", "--enable-pubsub-experiment", "--api", "/ip4/0.0.0.0/tcp/5001", "--routing", "dhtclient"]
  #   ports:
  #     - "4001:4001" # ipfs swarm
  #     - "5001:5001" # expose if needed/wanted
  #     - "8080:8080" # exposes if needed/wanted
  #   volumes:
  #     - ./compose/ipfs0:/data/ipfs
  #   environment:
  #     LIBP2P_FORCE_PNET: "1"
  #     LIBP2P_PNET_KEY: "/data/ipfs/swarm.key"  

  # ipfs1:
  #   container_name: ipfs1
  #   image: ipfs/go-ipfs:latest
  #   command: ["daemon", "--enable-pubsub-experiment", "--api", "/ip4/0.0.0.0/tcp/5101", "--routing", "dhtclient"]
  #   ports:
  #     - "4101:4001" # ipfs swarm
  #     - "5101:5001" # expose if needed/wanted
  #     - "8180:8080" # exposes if needed/wanted
  #   volumes:
  #     - ./compose/ipfs1:/data/ipfs/
  #   depends_on:
  #     - ipfs0
  #   environment:
  #     LIBP2P_FORCE_PNET: "1"  
  #     LIBP2P_PNET_KEY: "/data/ipfs/swarm.key"
  #     IPFS_BOOTSTRAP: /ip4/ipfs0/tcp/4001/p2p/12D3KooWEbcsuQ4eCnTfg3ar8Qo3N8Wkb4xqzoYtuTQcczhPQHZv
  #     export:     


  # ipfs0:
  #   container_name: ipfs0
  #   image: ipfs/go-ipfs:latest
  #   command: ["daemon", "--enable-pubsub-experiment", "--api", "/ip4/0.0.0.0/tcp/5001"]
  #   ports:
  #         - "4001:4001" # ipfs swarm
  #         - "5001:5001" # expose if needed/wanted
  #         - "8080:8080" # exposes if needed/wanted
  #   volumes:
  #     - ./compose/ipfs0:/data/ipfs
      
  # ipfs1:
  #   container_name: ipfs1
  #   image: ipfs/go-ipfs:latest
  #   command: ["daemon", "--enable-pubsub-experiment", "--api", "/ip4/0.0.0.0/tcp/5101"]
  #   ports:
  #         - "4101:4001" # ipfs swarm
  #         - "5101:5001" # expose if needed/wanted
  #         - "8180:8080" # exposes if needed/wanted
  #   volumes:
  #     - ./compose/ipfs1:/data/ipfs

# localhost:5001/webui/
# localhost:5101/webui/
# localhost:8080/ipfs/
# localhost:8180/ipfs/


#ipfs0->12D3KooWEbcsuQ4eCnTfg3ar8Qo3N8Wkb4xqzoYtuTQcczhPQHZv
#ipfs1->12D3KooWHH1h4SDBn5ZhKWUUrN8r37Wh8q8fU9ERUfGYQddp3LoB
